### ISSUE TITLE
Crash upon exiting villager painting trade menu

### ISSUE THREAD

**Issue by A00826925** [dantaeusb-mc/ZetterGallery#17]
I have yet to do more testing, but exiting the villager trade menu crashes the game, doesn't matter if i bought a painting or not. After the crash i get the following error in the launcher: 

The game crashed whilst keypressed event handler
Error: java.lang.IllegalArgumentException: Attempted to set event phase to NORMAL when already NORMAL

This was tested inside a modpack, so another mod may be the issue, i can share it with you later if you need it, just send me a mail.

**Comment by dantaeusb** [comment]
Hi, I need more details, I feel like. I tried to dig down with the information I have, and all I can say is that this might theoretically happen with `﻿net.minecraftforge.event.entity.player.PlayerContainerEvent.Close` event invoked twice somehow, but under normal conditions (only one mod), it happens only once. In order to be able to dive into it, I'll need:
a) Crash log, typically it's in crash-reports folder of Minecraft;
b) List of installed mods (I believe crash log also contains that list). But perfectly, if you know which mods are adjusting Villagers professions, or in-game GUIs, highlight them, please.

**Comment by A00826925** [comment]
ive modified the pack a bit since, but after enabling zetter gallery again i encountered two crashes:

1: i think this first one has nothing to do with you, but i had a crash with Obscure API from aquamirae after enabling zetter gallery, this was resolved on next boot, but i will leave the report just in case.
[obscureAPIcrashonboot.txt](https://github.com/dantaeusb-mc/ZetterGallery/files/10371048/obscureAPIcrashonboot.txt)

2: this is the originally reported crash, however i discovered something. If i open and quickly exit (the villager menu) just before an image loads, nothing happens, the game runs fine. But if i let the image load and then exit, the game crashes. 
[crashuponexitafterimageload.txt](https://github.com/dantaeusb-mc/ZetterGallery/files/10371050/crashuponexitafterimageload.txt)

im using the mod that adds more villager proffesions, mods that have images like tiny frame and the camera mod, but these last two dont have anything to do with villagers.

**Comment by dantaeusb** [comment]
Okay, thank you very much for the detailed report. From first glance, it appears that it's because both Zetter Gallery and MouseTweaks try to transform the same thing in Minecraft code. I'll try to fix that ASAP.

**Comment by dantaeusb** [comment]
Apparently it was Zetter bug, please update to 0.19.2 version and let me know if that helped. Updated files should be shortly available on CurseForge. Link for 1.19.2: https://www.curseforge.com/minecraft/mc-mods/zetter/files/4325323 (could be 404 for a while until CurseForge approves)

**Comment by A00826925** [comment]
seems to be resolved! thanks!
